apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-server
  labels:
    name: test-server
  annotations:
    name: test-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app:  test-server
    spec:
      restartPolicy: Always
      containers:
      - name: test-server
        image: test-php
        imagePullPolicy: Never
        command: ["php-fpm"]
        ports:
        - containerPort: 9000