apiVersion: v1
kind: Service
metadata:
  name: test-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30010
    #argetPort: nginx-port
    #protocol: TCP
  selector:
    app: test-nginx