apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-nginx
  labels:
    name: test-nginx
  annotations:
    name: test-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  test-nginx
    spec:
      restartPolicy: Always
      containers:
      - name: test-nginx
        image: test-nginx
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["-c", "nginx -g 'daemon off;'"]
        ports:
          - name: http
            containerPort: 80